/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 16-okt-2022 16:33:28 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */



/* Create Tables */

CREATE TABLE [Address]
(
	[AddressID] uniqueidentifier NOT NULL,
	[Street] varchar(30) NULL,
	[State] varchar(20) NULL,
	[Zip Code] varchar(6) NULL,
	[CityID] uniqueidentifier NULL
)
GO

CREATE TABLE [Administrator]
(
	[AministratorID] uniqueidentifier NOT NULL,
	[FirstName] varchar(30) NULL,
	[LastName] varchar(30) NULL,
	[ApplicationUserID] uniqueidentifier NULL,
	[Email] varchar(30) NULL,
	[ImageID] uniqueidentifier NULL
)
GO

CREATE TABLE [ApplicationUser]
(
	[ApplicationUserID] uniqueidentifier NOT NULL,
	[FirstName] varchar(50) NULL,
	[LastName] varchar(50) NULL,
	[TelephoneID] uniqueidentifier NULL,
	[AddressID] uniqueidentifier NULL,
	[RegistrationDate] datetime NULL,
	[UserName] varchar(20) NULL,
	[Email] varchar(30) NULL,
	[Password] varchar(50) NULL,
	[EmailConfirmed] int NULL
)
GO

CREATE TABLE [Category]
(
	[CatagoryID] uniqueidentifier NOT NULL,
	[Name] varchar(30) NULL,
	[CreatedDateTime] datetime NULL
)
GO

CREATE TABLE [City]
(
	[CityID] uniqueidentifier NOT NULL,
	[CityName] varchar(50) NULL,
	[RegionID] uniqueidentifier NULL
)
GO

CREATE TABLE [Company]
(
	[CompanyID] uniqueidentifier NOT NULL,
	[Name] varchar(25) NULL,
	[AddressID] uniqueidentifier NULL,
	[OrderID] int NULL,
	[TelephoneID] uniqueidentifier NULL
)
GO

CREATE TABLE [Customer]
(
	[CustomerID] uniqueidentifier NOT NULL,
	[FirstName] varchar(20) NULL,
	[LastName] varchar(20) NULL,
	[AddressID] uniqueidentifier NULL,
	[Email] varchar(50) NULL,
	[TelephoneID] uniqueidentifier NULL,
	[ApplicationUserID] uniqueidentifier NULL
)
GO

CREATE TABLE [Employee]
(
	[EmployeeId] uniqueidentifier NOT NULL,
	[FirstName] varchar(50) NULL,
	[LastName] varchar(50) NULL,
	[Title] varchar(50) NULL,
	[AddressID] varchar(50) NULL,
	[CompanyID] uniqueidentifier NULL,
	[ApplicationUserID] uniqueidentifier NULL,
	[ImageID] uniqueidentifier NULL
)
GO

CREATE TABLE [Image]
(
	[ImageID] uniqueidentifier NOT NULL,
	[FileName] varchar(30) NULL,
	[FileType] varchar(10) NULL
)
GO

CREATE TABLE [Order_Details]
(
	[OrderID] uniqueidentifier NOT NULL,
	[ProductID] uniqueidentifier NULL,
	[UnitPrice] int NULL,
	[Quantity] int NULL
)
GO

CREATE TABLE [OrderReview]
(
	[OrderReviewID] uniqueidentifier NOT NULL,
	[Rating] int NULL,
	[CreateDate] datetime NULL,
	[OrderID] uniqueidentifier NULL
)
GO

CREATE TABLE [OrderShopping]
(
	[OrderID] uniqueidentifier NOT NULL,
	[Order_Date] datetime NULL,
	[Requaired_Date] datetime NULL,
	[CompanyID] varchar(10) NULL,
	[Shipped_Date] datetime NULL,
	[OrderStatus] varchar(20) NULL,
	[PaymentStatus] varchar(20) NULL,
	[PaymentDate] datetime NULL,
	[AddressID] uniqueidentifier NULL,
	[ProductID] uniqueidentifier NULL,
	[ApplicationUserID] uniqueidentifier NULL,
	[TelephoneID] uniqueidentifier NULL,
	[ApplicationUser] nvarchar(50) NULL
)
GO

CREATE TABLE [Product]
(
	[ProductID] uniqueidentifier NOT NULL,
	[Tittle] varchar(30) NULL,
	[Description] varchar(50) NULL,
	[PurchasePrice] decimal(10,2) NULL,
	[Status] varchar(15) NULL,
	[CreateTime] datetime NULL,
	[ImageID] uniqueidentifier NULL,
	[CompanyID] uniqueidentifier NULL
)
GO

CREATE TABLE [Product_Category]
(
	[CatagoryID] uniqueidentifier NULL,
	[ProductID] uniqueidentifier NULL
)
GO

CREATE TABLE [Region]
(
	[RegionID] uniqueidentifier NOT NULL,
	[RegionName] varchar(50) NULL
)
GO

CREATE TABLE [Roles]
(
	[RolesID] uniqueidentifier NOT NULL,
	[Name] varchar(25) NULL,
	[NormalizedName] varchar(25) NULL,
	[ConcurrencyStamp] varchar(25) NULL
)
GO

CREATE TABLE [ShoppinCart]
(
	[CartID] uniqueidentifier NOT NULL,
	[ProductID] uniqueidentifier NULL,
	[Count] varchar(50) NULL,
	[ApplicationUserID] uniqueidentifier NULL,
	[Price] decimal(10,2) NULL,
	[Status] varchar(20) NULL
)
GO

CREATE TABLE [Telephone]
(
	[TelephoneID] uniqueidentifier NOT NULL,
	[PhoneNr] varchar(11) NULL
)
GO

CREATE TABLE [UserRoles]
(
	[RolesID] uniqueidentifier NOT NULL,
	[ApplicationUserID] uniqueidentifier NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Address] 
 ADD CONSTRAINT [PK_Adress]
	PRIMARY KEY CLUSTERED ([AddressID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Address_City] 
 ON [Address] ([CityID] ASC)
GO

ALTER TABLE [Administrator] 
 ADD CONSTRAINT [PK_Administrator]
	PRIMARY KEY CLUSTERED ([AministratorID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Administrator_Image] 
 ON [Administrator] ([ImageID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Aministrator_ApplicationUser] 
 ON [Administrator] ([ApplicationUserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Employee_ApplicationUser] 
 ON [Administrator] ([ApplicationUserID] ASC)
GO

ALTER TABLE [ApplicationUser] 
 ADD CONSTRAINT [PK_ApplicationUser]
	PRIMARY KEY CLUSTERED ([ApplicationUserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_ApplicationUser_Address] 
 ON [ApplicationUser] ([AddressID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_ApplicationUser_Telefon] 
 ON [ApplicationUser] ([TelephoneID] ASC)
GO

ALTER TABLE [Category] 
 ADD CONSTRAINT [PK_Category]
	PRIMARY KEY CLUSTERED ([CatagoryID] ASC)
GO

ALTER TABLE [City] 
 ADD CONSTRAINT [PK_City]
	PRIMARY KEY CLUSTERED ([CityID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_City_Region] 
 ON [City] ([RegionID] ASC)
GO

ALTER TABLE [Company] 
 ADD CONSTRAINT [PK_Company]
	PRIMARY KEY CLUSTERED ([CompanyID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Company_Telephone] 
 ON [Company] ([TelephoneID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Company_Address] 
 ON [Company] ([AddressID] ASC)
GO

ALTER TABLE [Customer] 
 ADD CONSTRAINT [PK_Customer]
	PRIMARY KEY CLUSTERED ([CustomerID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Customer_ApplicationUser] 
 ON [Customer] ([ApplicationUserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Customer_Telephone] 
 ON [Customer] ([TelephoneID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Customer_Address] 
 ON [Customer] ([AddressID] ASC)
GO

ALTER TABLE [Employee] 
 ADD CONSTRAINT [PK_Employee]
	PRIMARY KEY CLUSTERED ([EmployeeId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Employee_ApplicationUser] 
 ON [Employee] ([ApplicationUserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Employee_Image] 
 ON [Employee] ([ImageID] ASC)
GO

ALTER TABLE [Image] 
 ADD CONSTRAINT [PK_Image]
	PRIMARY KEY CLUSTERED ([ImageID] ASC)
GO

ALTER TABLE [Order_Details] 
 ADD CONSTRAINT [PK_Order_Details]
	PRIMARY KEY CLUSTERED ([OrderID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Order_Details_Product] 
 ON [Order_Details] ([ProductID] ASC)
GO

ALTER TABLE [OrderReview] 
 ADD CONSTRAINT [PK_Order_review]
	PRIMARY KEY CLUSTERED ([OrderReviewID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_OrderReview_OrderShopping] 
 ON [OrderReview] ([OrderID] ASC)
GO

ALTER TABLE [OrderShopping] 
 ADD CONSTRAINT [PK_Order_Shoping]
	PRIMARY KEY CLUSTERED ([OrderID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Order_Shoping_Product] 
 ON [OrderShopping] ([ProductID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Order_Shoping_Telephone] 
 ON [OrderShopping] ([TelephoneID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_OrderShopping_Address] 
 ON [OrderShopping] ([AddressID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_OrderShopping_ApplicationUser] 
 ON [OrderShopping] ([ApplicationUserID] ASC)
GO

ALTER TABLE [Product] 
 ADD CONSTRAINT [PK_Product]
	PRIMARY KEY CLUSTERED ([ProductID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Product_Company] 
 ON [Product] ([CompanyID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Product_Image] 
 ON [Product] ([ImageID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Product_Category_Category] 
 ON [Product_Category] ([CatagoryID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Product_Category_Product] 
 ON [Product_Category] ([ProductID] ASC)
GO

ALTER TABLE [Region] 
 ADD CONSTRAINT [PK_Region]
	PRIMARY KEY CLUSTERED ([RegionID] ASC)
GO

ALTER TABLE [Roles] 
 ADD CONSTRAINT [PK_UserRoles]
	PRIMARY KEY CLUSTERED ([RolesID] ASC)
GO

ALTER TABLE [ShoppinCart] 
 ADD CONSTRAINT [PK_ShoppinCart]
	PRIMARY KEY CLUSTERED ([CartID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_ShoppinCart_ApplicationUser] 
 ON [ShoppinCart] ([ApplicationUserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_ShoppinCart_Product] 
 ON [ShoppinCart] ([ProductID] ASC)
GO

ALTER TABLE [Telephone] 
 ADD CONSTRAINT [PK_Telephone]
	PRIMARY KEY CLUSTERED ([TelephoneID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UserRoles_ApplicationUser] 
 ON [UserRoles] ([ApplicationUserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UserRoles_Roles] 
 ON [UserRoles] ([RolesID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Address] ADD CONSTRAINT [FK_Address_City]
	FOREIGN KEY ([CityID]) REFERENCES [City] ([CityID])
GO

ALTER TABLE [Administrator] ADD CONSTRAINT [FK_Administrator_Image]
	FOREIGN KEY ([ImageID]) REFERENCES [Image] ([ImageID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Administrator] ADD CONSTRAINT [FK_Aministrator_ApplicationUser]
	FOREIGN KEY ([ApplicationUserID]) REFERENCES  [ApplicationUser] ([ApplicationUserID])
GO

ALTER TABLE [Administrator] ADD CONSTRAINT [FK_Employee_ApplicationUser]
	FOREIGN KEY ([ApplicationUserID]) REFERENCES  [ApplicationUser] ([ApplicationUserID])
GO

ALTER TABLE [ApplicationUser] ADD CONSTRAINT [FK_ApplicationUser_Address]
	FOREIGN KEY ([AddressID]) REFERENCES [Address] ([AddressID])
GO

ALTER TABLE [ApplicationUser] ADD CONSTRAINT [FK_ApplicationUser_Telefon]
	FOREIGN KEY ([TelephoneID]) REFERENCES [Telephone] ([TelephoneID])
GO

ALTER TABLE [City] ADD CONSTRAINT [FK_City_Region]
	FOREIGN KEY ([RegionID]) REFERENCES [Region] ([RegionID])
GO

ALTER TABLE [Company] ADD CONSTRAINT [FK_Company_Address]
	FOREIGN KEY ([AddressID]) REFERENCES [Address] ([AddressID])
GO

ALTER TABLE [Company] ADD CONSTRAINT [FK_Company_Telephone]
	FOREIGN KEY ([TelephoneID]) REFERENCES [Telephone] ([TelephoneID])
GO

ALTER TABLE [Customer] ADD CONSTRAINT [FK_Customer_Address]
	FOREIGN KEY ([AddressID]) REFERENCES [Address] ([AddressID])
GO

ALTER TABLE [Customer] ADD CONSTRAINT [FK_Customer_ApplicationUser]
	FOREIGN KEY ([ApplicationUserID]) REFERENCES  [ApplicationUser] ([ApplicationUserID])
GO

ALTER TABLE [Customer] ADD CONSTRAINT [FK_Customer_Telephone]
	FOREIGN KEY ([TelephoneID]) REFERENCES [Telephone] ([TelephoneID])
GO

ALTER TABLE [Employee] ADD CONSTRAINT [FK_Employee_ApplicationUser]
	FOREIGN KEY ([ApplicationUserID]) REFERENCES  [ApplicationUser] ([ApplicationUserID])
GO

ALTER TABLE [Employee] ADD CONSTRAINT [FK_Employee_Image]
	FOREIGN KEY ([ImageID]) REFERENCES [Image] ([ImageID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Order_Details] ADD CONSTRAINT [FK_Order_Details_Product]
	FOREIGN KEY ([ProductID]) REFERENCES [Product] ([ProductID])
GO

ALTER TABLE [OrderReview] ADD CONSTRAINT [FK_OrderReview_OrderShopping]
	FOREIGN KEY ([OrderID]) REFERENCES [OrderShopping] ([OrderID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [OrderShopping] ADD CONSTRAINT [FK_OrderShopping_Address]
	FOREIGN KEY ([AddressID]) REFERENCES [Address] ([AddressID])
GO

ALTER TABLE [OrderShopping] ADD CONSTRAINT [FK_OrderShopping_ApplicationUser]
	FOREIGN KEY ([ApplicationUserID]) REFERENCES  [ApplicationUser] ([ApplicationUserID])
GO

ALTER TABLE [OrderShopping] ADD CONSTRAINT [FK_OrderShopping_Product]
	FOREIGN KEY ([ProductID]) REFERENCES [Product] ([ProductID])
GO

ALTER TABLE [OrderShopping] ADD CONSTRAINT [FK_OrderShopping_Telephone]
	FOREIGN KEY ([TelephoneID]) REFERENCES [Telephone] ([TelephoneID])
GO

ALTER TABLE [Product] ADD CONSTRAINT [FK_Product_Company]
	FOREIGN KEY ([CompanyID]) REFERENCES [Company] ([CompanyID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Product] ADD CONSTRAINT [FK_Product_Image]
	FOREIGN KEY ([ImageID]) REFERENCES [Image] ([ImageID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Product_Category] ADD CONSTRAINT [FK_Product_Category_Category]
	FOREIGN KEY ([CatagoryID]) REFERENCES [Category] ([CatagoryID])
GO

ALTER TABLE [Product_Category] ADD CONSTRAINT [FK_Product_Category_Product]
	FOREIGN KEY ([ProductID]) REFERENCES [Product] ([ProductID])
GO

ALTER TABLE [ShoppinCart] ADD CONSTRAINT [FK_ShoppinCart_ApplicationUser]
	FOREIGN KEY ([ApplicationUserID]) REFERENCES  [ApplicationUser] ([ApplicationUserID])
GO

ALTER TABLE [ShoppinCart] ADD CONSTRAINT [FK_ShoppinCart_Product]
	FOREIGN KEY ([ProductID]) REFERENCES [Product] ([ProductID])
GO

ALTER TABLE [UserRoles] ADD CONSTRAINT [FK_UserRoles_ApplicationUser]
	FOREIGN KEY ([ApplicationUserID]) REFERENCES  [ApplicationUser] ([ApplicationUserID])
GO

ALTER TABLE [UserRoles] ADD CONSTRAINT [FK_UserRoles_Roles]
	FOREIGN KEY ([RolesID]) REFERENCES [Roles] ([RolesID])
GO
